// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UrlsColumns holds the columns for the "urls" table.
	UrlsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 32, SchemaType: map[string]string{"postgres": "varchar(32)"}},
		{Name: "created_at", Type: field.TypeTime, Default: "NOW()", SchemaType: map[string]string{"postgres": "TIMESTAMP"}},
		{Name: "updated_at", Type: field.TypeTime, Default: "NOW()", SchemaType: map[string]string{"postgres": "TIMESTAMP"}},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "TIMESTAMP"}},
		{Name: "destination", Type: field.TypeString, SchemaType: map[string]string{"postgres": "TEXT"}},
		{Name: "user_id", Type: field.TypeInt64, SchemaType: map[string]string{"postgres": "BIGINT"}},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "TIMESTAMP"}},
	}
	// UrlsTable holds the schema information for the "urls" table.
	UrlsTable = &schema.Table{
		Name:       "urls",
		Columns:    UrlsColumns,
		PrimaryKey: []*schema.Column{UrlsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ix_urls_user_active",
				Unique:  false,
				Columns: []*schema.Column{UrlsColumns[5], UrlsColumns[2]},
				Annotation: &entsql.IndexAnnotation{
					Where: "deleted_at IS NULL",
				},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UrlsTable,
	}
)

func init() {
	UrlsTable.Annotation = &entsql.Annotation{
		Table: "urls",
	}
}
