// Code generated by ent, DO NOT EDIT.

package ent

import (
	"URLShortner/internal/infrastructure/persistence/ent/schema"
	"URLShortner/internal/infrastructure/persistence/ent/urls"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	urlsMixin := schema.Urls{}.Mixin()
	urlsMixinFields0 := urlsMixin[0].Fields()
	_ = urlsMixinFields0
	urlsFields := schema.Urls{}.Fields()
	_ = urlsFields
	// urlsDescCreatedAt is the schema descriptor for created_at field.
	urlsDescCreatedAt := urlsMixinFields0[0].Descriptor()
	// urls.DefaultCreatedAt holds the default value on creation for the created_at field.
	urls.DefaultCreatedAt = urlsDescCreatedAt.Default.(func() time.Time)
	// urlsDescUpdatedAt is the schema descriptor for updated_at field.
	urlsDescUpdatedAt := urlsMixinFields0[1].Descriptor()
	// urls.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	urls.DefaultUpdatedAt = urlsDescUpdatedAt.Default.(func() time.Time)
	// urls.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	urls.UpdateDefaultUpdatedAt = urlsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// urlsDescDestination is the schema descriptor for destination field.
	urlsDescDestination := urlsFields[1].Descriptor()
	// urls.DestinationValidator is a validator for the "destination" field. It is called by the builders before save.
	urls.DestinationValidator = urlsDescDestination.Validators[0].(func(string) error)
	// urlsDescID is the schema descriptor for id field.
	urlsDescID := urlsFields[0].Descriptor()
	// urls.IDValidator is a validator for the "id" field. It is called by the builders before save.
	urls.IDValidator = func() func(string) error {
		validators := urlsDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
