// Code generated by ent, DO NOT EDIT.

package ent

import (
	"URLShortner/internal/infrastructure/persistence/ent/urls"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UrlsCreate is the builder for creating a Urls entity.
type UrlsCreate struct {
	config
	mutation *UrlsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UrlsCreate) SetCreatedAt(v time.Time) *UrlsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UrlsCreate) SetNillableCreatedAt(v *time.Time) *UrlsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UrlsCreate) SetUpdatedAt(v time.Time) *UrlsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UrlsCreate) SetNillableUpdatedAt(v *time.Time) *UrlsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UrlsCreate) SetDeletedAt(v time.Time) *UrlsCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UrlsCreate) SetNillableDeletedAt(v *time.Time) *UrlsCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDestination sets the "destination" field.
func (_c *UrlsCreate) SetDestination(v string) *UrlsCreate {
	_c.mutation.SetDestination(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UrlsCreate) SetUserID(v int64) *UrlsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UrlsCreate) SetExpiresAt(v time.Time) *UrlsCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UrlsCreate) SetNillableExpiresAt(v *time.Time) *UrlsCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UrlsCreate) SetID(v string) *UrlsCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UrlsMutation object of the builder.
func (_c *UrlsCreate) Mutation() *UrlsMutation {
	return _c.mutation
}

// Save creates the Urls in the database.
func (_c *UrlsCreate) Save(ctx context.Context) (*Urls, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UrlsCreate) SaveX(ctx context.Context) *Urls {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UrlsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UrlsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UrlsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := urls.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := urls.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UrlsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Urls.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Urls.updated_at"`)}
	}
	if _, ok := _c.mutation.Destination(); !ok {
		return &ValidationError{Name: "destination", err: errors.New(`ent: missing required field "Urls.destination"`)}
	}
	if v, ok := _c.mutation.Destination(); ok {
		if err := urls.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "Urls.destination": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Urls.user_id"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := urls.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Urls.id": %w`, err)}
		}
	}
	return nil
}

func (_c *UrlsCreate) sqlSave(ctx context.Context) (*Urls, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Urls.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UrlsCreate) createSpec() (*Urls, *sqlgraph.CreateSpec) {
	var (
		_node = &Urls{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(urls.Table, sqlgraph.NewFieldSpec(urls.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(urls.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(urls.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(urls.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Destination(); ok {
		_spec.SetField(urls.FieldDestination, field.TypeString, value)
		_node.Destination = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(urls.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(urls.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// UrlsCreateBulk is the builder for creating many Urls entities in bulk.
type UrlsCreateBulk struct {
	config
	err      error
	builders []*UrlsCreate
}

// Save creates the Urls entities in the database.
func (_c *UrlsCreateBulk) Save(ctx context.Context) ([]*Urls, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Urls, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UrlsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UrlsCreateBulk) SaveX(ctx context.Context) []*Urls {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UrlsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UrlsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
