// Code generated by ent, DO NOT EDIT.

package ent

import (
	"URLShortner/internal/infrastructure/persistence/ent/predicate"
	"URLShortner/internal/infrastructure/persistence/ent/urls"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UrlsUpdate is the builder for updating Urls entities.
type UrlsUpdate struct {
	config
	hooks    []Hook
	mutation *UrlsMutation
}

// Where appends a list predicates to the UrlsUpdate builder.
func (_u *UrlsUpdate) Where(ps ...predicate.Urls) *UrlsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UrlsUpdate) SetUpdatedAt(v time.Time) *UrlsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UrlsUpdate) SetDeletedAt(v time.Time) *UrlsUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UrlsUpdate) SetNillableDeletedAt(v *time.Time) *UrlsUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UrlsUpdate) ClearDeletedAt() *UrlsUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDestination sets the "destination" field.
func (_u *UrlsUpdate) SetDestination(v string) *UrlsUpdate {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *UrlsUpdate) SetNillableDestination(v *string) *UrlsUpdate {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UrlsUpdate) SetExpiresAt(v time.Time) *UrlsUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UrlsUpdate) SetNillableExpiresAt(v *time.Time) *UrlsUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UrlsUpdate) ClearExpiresAt() *UrlsUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the UrlsMutation object of the builder.
func (_u *UrlsUpdate) Mutation() *UrlsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UrlsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UrlsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UrlsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UrlsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UrlsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := urls.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UrlsUpdate) check() error {
	if v, ok := _u.mutation.Destination(); ok {
		if err := urls.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "Urls.destination": %w`, err)}
		}
	}
	return nil
}

func (_u *UrlsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(urls.Table, urls.Columns, sqlgraph.NewFieldSpec(urls.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(urls.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(urls.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(urls.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(urls.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(urls.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(urls.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{urls.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UrlsUpdateOne is the builder for updating a single Urls entity.
type UrlsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UrlsMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UrlsUpdateOne) SetUpdatedAt(v time.Time) *UrlsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UrlsUpdateOne) SetDeletedAt(v time.Time) *UrlsUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UrlsUpdateOne) SetNillableDeletedAt(v *time.Time) *UrlsUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UrlsUpdateOne) ClearDeletedAt() *UrlsUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDestination sets the "destination" field.
func (_u *UrlsUpdateOne) SetDestination(v string) *UrlsUpdateOne {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *UrlsUpdateOne) SetNillableDestination(v *string) *UrlsUpdateOne {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UrlsUpdateOne) SetExpiresAt(v time.Time) *UrlsUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UrlsUpdateOne) SetNillableExpiresAt(v *time.Time) *UrlsUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UrlsUpdateOne) ClearExpiresAt() *UrlsUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the UrlsMutation object of the builder.
func (_u *UrlsUpdateOne) Mutation() *UrlsMutation {
	return _u.mutation
}

// Where appends a list predicates to the UrlsUpdate builder.
func (_u *UrlsUpdateOne) Where(ps ...predicate.Urls) *UrlsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UrlsUpdateOne) Select(field string, fields ...string) *UrlsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Urls entity.
func (_u *UrlsUpdateOne) Save(ctx context.Context) (*Urls, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UrlsUpdateOne) SaveX(ctx context.Context) *Urls {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UrlsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UrlsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UrlsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := urls.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UrlsUpdateOne) check() error {
	if v, ok := _u.mutation.Destination(); ok {
		if err := urls.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "Urls.destination": %w`, err)}
		}
	}
	return nil
}

func (_u *UrlsUpdateOne) sqlSave(ctx context.Context) (_node *Urls, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(urls.Table, urls.Columns, sqlgraph.NewFieldSpec(urls.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Urls.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, urls.FieldID)
		for _, f := range fields {
			if !urls.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != urls.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(urls.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(urls.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(urls.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(urls.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(urls.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(urls.FieldExpiresAt, field.TypeTime)
	}
	_node = &Urls{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{urls.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
