// Code generated by ent, DO NOT EDIT.

package ent

import (
	"URLShortner/internal/infrastructure/persistence/ent/predicate"
	"URLShortner/internal/infrastructure/persistence/ent/urls"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UrlsDelete is the builder for deleting a Urls entity.
type UrlsDelete struct {
	config
	hooks    []Hook
	mutation *UrlsMutation
}

// Where appends a list predicates to the UrlsDelete builder.
func (_d *UrlsDelete) Where(ps ...predicate.Urls) *UrlsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UrlsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UrlsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UrlsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(urls.Table, sqlgraph.NewFieldSpec(urls.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UrlsDeleteOne is the builder for deleting a single Urls entity.
type UrlsDeleteOne struct {
	_d *UrlsDelete
}

// Where appends a list predicates to the UrlsDelete builder.
func (_d *UrlsDeleteOne) Where(ps ...predicate.Urls) *UrlsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UrlsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{urls.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UrlsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
